# Notes:
# 1. Conda searches for packages in the channels listed below, in the order given
# 2. For some packages the channels may defined explicitly (i.e. channel::package=version)

name: droids-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.4
  - jupyter
  - pip
  - spacy
  - pip:
      - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.0.0/en_core_web_sm-2.0.0.tar.gz
